### PR TITLE
Russian and Belarusian translations

### PR DESCRIPTION
**Pull request by R0bur**

### CODE REVIEW

**Comment by thewaiter** [comment]
Thx mate :)

**Comment by R0bur** [comment]
You're welcome! ;-)

**Comment by thewaiter** [comment]
May I ask you for this module translation also?
https://github.com/BodhiDev/Desktitle2.0

Thx

**Comment by R0bur** [comment]
Sure. Ready: https://github.com/BodhiDev/Desktitle2.0/pull/4

**Pull request merged**
